/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7bf0bb8e3bac4154d554ed869360e2a4)
interface __BaseEnv_Env {
	DB: D1Database;
	ANALYTICS: AnalyticsEngineDataset;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	RESEND_API_KEY: string;
	CF_ACCOUNT_ID: "79a56f7656f972b064b9d4ec3662b8d0";
	ADMIN_USER_IDS: "github:2826376,github:local-staging-tester" | "github:2826376";
	ANALYTICS_DATASET: "aat_events_staging" | "aat_events";
	GOOGLE_CLIENT_ID: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	CF_ANALYTICS_TOKEN: string;
}
declare namespace Cloudflare {
	interface StagingEnv {
		DB: D1Database;
		ANALYTICS: AnalyticsEngineDataset;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
		RESEND_API_KEY: string;
		CF_ACCOUNT_ID: "79a56f7656f972b064b9d4ec3662b8d0";
		ADMIN_USER_IDS: "github:2826376,github:local-staging-tester";
		ANALYTICS_DATASET: "aat_events_staging";
		GOOGLE_CLIENT_ID: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		CF_ANALYTICS_TOKEN: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCOUNT_ID" | "ADMIN_USER_IDS" | "ANALYTICS_DATASET" | "GOOGLE_CLIENT_ID" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "CF_ANALYTICS_TOKEN" | "RESEND_API_KEY">> {}
}
